apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-helm
  name: {{ .Release.Name }}-helm
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-helm
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      labels:
        app: nginx-helm
    spec:
      containers:
      - image: {{ .Values.image.repository }} 
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: nginx
        volumeMounts:
          - mountPath: "/etc/nginx/ssl"
            name: nginx-ssl
          - mountPath: /etc/nginx/conf.d
            name: configmap-volume 
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: nginx-ssl
          secret:
            secretName: nginx-ssl
        - name: configmap-volume
          configMap:
            name: nginx-configmap 
      dnsPolicy: {{ .Values.dnsPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      schedulerName: {{ .Values.schedulerName }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
