apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-helm
  name: nginx-helm
  namespace: default
spec:
  ports:
  - name: 80-80
    # nodePort: 31917
    port: 80
    protocol: TCP
    targetPort: 80
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-helm
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}