apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-helm
  name: {{ .Release.Name }}-helm
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-helm
  sessionAffinity: None
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}