apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.chart" . }}
  labels:
    app: {{ include "nginx.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nginx.chart" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx.chart" . }}
    spec:
      containers:
      - name: nginx
        image: "nginx:1.16.0"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: ssl
          mountPath: /etc/nginx/ssl
      volumes:
      - name: ssl
        secret:
          secretName: nginx-certs